import os
from langchain_ollama import ChatOllama
from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv
import os
import time  # NEW IMPORT

load_dotenv()  
# Initialize both models
try:
    cloud_llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash", 
        google_api_key=os.getenv("GOOGLE_API_KEY"),
        max_retries=0  # Forces immediate failure on quota errors
    )

    local_llm = ChatOllama(model="llama3.2", temperature=0.1)


except Exception as e:
    print("ERROR initializing LLMS :\n\n ",e)


# Add chat_history as the third parameter
def think_and_stream(text, memory_context, chat_history):
    # ---------------------------------------------------------
    # 1. THE LOCAL INSTRUCTION (The Secret Code)
    # ---------------------------------------------------------
    local_system_prompt = f"""You are RUA, a fast AI running locally. Memory Context: {memory_context}.
    CRITICAL RULE: If the user asks for complex coding, deep factual knowledge, or a task you are unsure how to do perfectly, your VERY FIRST word MUST be "ESCALATE". 
    If you CAN answer it yourself (like basic chat, greetings, or simple tasks), answer normally. Keep it witty, brief, and under 20 words."""

    # Build the message array dynamically: System -> History -> Current Prompt
    messages = [{"role": "system", "content": local_system_prompt}]
    messages.extend(chat_history)  # Inject the short-term memory here
    messages.append({"role": "user", "content": text})

    needs_cloud = False
    
    # ---------------------------------------------------------
    # 2. LOCAL ATTEMPT & INTERCEPTION
    # ---------------------------------------------------------
    try:
        local_iterator = local_llm.stream(messages)
        
        # Peek at the very first chunk generated by the local LLM
        first_chunk = next(local_iterator)
        first_content = first_chunk.content if hasattr(first_chunk, 'content') else str(first_chunk)

        # Check if the local LLM hit the panic button
        if "ESCALATE" in first_content.upper():
            needs_cloud = True
        else:
            # It's a valid local answer! Yield the first chunk, then stream the rest
            yield first_content
            for chunk in local_iterator:
                yield chunk.content if hasattr(chunk, 'content') else str(chunk)

    except StopIteration:
        pass # Empty response from local
    except Exception as e:
        # If Ollama crashes or is offline, instantly fail over to cloud
        print("\n⚠️ Local brain offline or errored. Switching to Cloud...")
        needs_cloud = True

    # ---------------------------------------------------------
    # 3. CLOUD ESCALATION (Runs only if needed)
    # ---------------------------------------------------------
    if needs_cloud:
        print("\n☁️ Routing to Cloud Brain for complex task...", end="", flush=True)
        
        cloud_messages = [
            {"role": "system", "content": f"You are RUA. Witty, fast, brief. < 20 words. Memory: {memory_context}"},
            {"role": "user", "content": text}
        ]
        
        try:
            for chunk in cloud_llm.stream(cloud_messages):
                yield chunk.content if hasattr(chunk, 'content') else str(chunk)
        except Exception as e:
            yield " Sorry boss, both my local and cloud brains are fried right now."



def update_long_term_memory(user_text, rua_brain):
    """Silent background task to extract facts without slowing down the chat."""
    prompt = f"""Analyze the following user statement: "{user_text}"
    If the user is stating a permanent fact about themselves (like their name, age, job, or likes), extract it as a short, 3-to-5 word fact (e.g., "User's name is Anish").
    If it is just normal conversation, a command, or a question, reply with EXACTLY the word "NONE".
    Answer:"""
    
    try:
        import time # Ensured import inside the thread just in case
        
        response = local_llm.invoke(prompt)
        fact = response.content.strip()
        
        # DEBUG: This will print exactly what Llama generated so we can see its "thoughts"
        print(f"\n🕵️ [Debug - Raw LLM Memory Output]: {fact}")
        
        if "NONE" not in fact.upper() and len(fact) > 3:
            # Clean up Llama's tendency to be chatty (e.g., "Here is the fact: User is a boy")
            if ":" in fact:
                fact = fact.split(":")[-1].strip()
                
            # Strip out weird markdown, quotes, or newlines it might add
            fact = fact.replace('"', '').replace('*', '').split('\n')[0].strip()
            
            # Save it
            key = f"fact_{int(time.time())}"
            rua_brain.learn_fact(key, fact)
            print(f"\n🧠 [Memory Stored Permanently]: {fact}")
            print("\n💤 RUA is sleeping. Say 'Jarvis' to wake...") # Refresh the terminal prompt
            
    except Exception as e:
        # Stop hiding errors!
        print(f"\n⚠️ Memory Thread Error: {e}")