# import os
# from langchain_ollama import ChatOllama
# from langchain_google_genai import ChatGoogleGenerativeAI
# from dotenv import load_dotenv
# import os

# load_dotenv()  
# # Initialize both models
# try:
#     cloud_llm = ChatGoogleGenerativeAI(
#         model="gemini-2.5-flash", 
#         google_api_key=os.getenv("GOOGLE_API_KEY"),
#         max_retries=0  # Forces immediate failure on quota errors
#     )

#     local_llm = ChatOllama(model="llama3.2", temperature=0.1)


# except Exception as e:
#     print("ERROR initializing LLMS :\n\n ",e)



# def think_and_stream(text, memory_context):
#     messages = [
#         {"role": "system", "content": f"You are RUA. Witty, fast, brief. No markdown. < 20 words. Memory Context: {memory_context}"},
#         {"role": "user", "content": text}
#     ]

#     # Decide initial routing: try cloud if query is > 10 chars
#     try_cloud = len(text) > 10

#     if try_cloud:
#         try:
#             # Attempt Cloud LLM first
#             for chunk in cloud_llm.stream(messages):
#                 yield chunk.content if hasattr(chunk, 'content') else str(chunk)
#             return  # If successful, exit the function so it doesn't run the local LLM
            
#         except Exception as e:
#             # If we hit a 429 Quota Error or network drop, catch it and print a warning
#             print("\n⚠️ Cloud limit reached. Falling back to Local Llama...", end="", flush=True)
#             # Do NOT return here. Let the code continue down to the local_llm block below.

#     # ---------------------------------------------------------
#     # LOCAL LLM FALLBACK (Runs if Cloud fails OR if query <= 10)
#     # ---------------------------------------------------------
#     try:
#         for chunk in local_llm.stream(messages):
#             yield chunk.content if hasattr(chunk, 'content') else str(chunk)
#     except Exception as e:
#         yield "System error. My local brain is offline."

import os
from langchain_ollama import ChatOllama
from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv
import os

load_dotenv()  
# Initialize both models
try:
    cloud_llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash", 
        google_api_key=os.getenv("GOOGLE_API_KEY"),
        max_retries=0  # Forces immediate failure on quota errors
    )

    local_llm = ChatOllama(model="llama3.2", temperature=0.1)


except Exception as e:
    print("ERROR initializing LLMS :\n\n ",e)


def think_and_stream(text, memory_context):
    # ---------------------------------------------------------
    # 1. THE LOCAL INSTRUCTION (The Secret Code)
    # ---------------------------------------------------------
    local_system_prompt = f"""You are RUA, a fast AI running locally. Memory Context: {memory_context}.
    CRITICAL RULE: If the user asks for complex coding, deep factual knowledge, or a task you are unsure how to do perfectly, your VERY FIRST word MUST be "ESCALATE". 
    If you CAN answer it yourself (like basic chat, greetings, or simple tasks), answer normally. Keep it witty, brief, and under 20 words."""

    messages = [
        {"role": "system", "content": local_system_prompt},
        {"role": "user", "content": text}
    ]

    needs_cloud = False

    # ---------------------------------------------------------
    # 2. LOCAL ATTEMPT & INTERCEPTION
    # ---------------------------------------------------------
    try:
        local_iterator = local_llm.stream(messages)
        
        # Peek at the very first chunk generated by the local LLM
        first_chunk = next(local_iterator)
        first_content = first_chunk.content if hasattr(first_chunk, 'content') else str(first_chunk)

        # Check if the local LLM hit the panic button
        if "ESCALATE" in first_content.upper():
            needs_cloud = True
        else:
            # It's a valid local answer! Yield the first chunk, then stream the rest
            yield first_content
            for chunk in local_iterator:
                yield chunk.content if hasattr(chunk, 'content') else str(chunk)

    except StopIteration:
        pass # Empty response from local
    except Exception as e:
        # If Ollama crashes or is offline, instantly fail over to cloud
        print("\n⚠️ Local brain offline or errored. Switching to Cloud...")
        needs_cloud = True

    # ---------------------------------------------------------
    # 3. CLOUD ESCALATION (Runs only if needed)
    # ---------------------------------------------------------
    if needs_cloud:
        print("\n☁️ Routing to Cloud Brain for complex task...", end="", flush=True)
        
        cloud_messages = [
            {"role": "system", "content": f"You are RUA. Witty, fast, brief. < 20 words. Memory: {memory_context}"},
            {"role": "user", "content": text}
        ]
        
        try:
            for chunk in cloud_llm.stream(cloud_messages):
                yield chunk.content if hasattr(chunk, 'content') else str(chunk)
        except Exception as e:
            yield " Sorry boss, both my local and cloud brains are fried right now."